# Generated by Django 4.2.4 on 2025-03-13 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignmentsettings_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradebook',
            name='user',
        ),
        migrations.AddField(
            model_name='submitassignment',
            name='studentNum',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentsettings',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 7, 28, 3, 270260, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='overallMarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradebook',
            name='studentNum',
            field=models.TextField(),
        ),
    ]
